"""Contains helper functions."""
from datetime import date


def build_commit_message(added, deleted, updated, subject=None):
    """Returns a nice commit message.

    Args:
        added (set): a set of API IDs that have been added.
        deleted (set): a set of API IDs that have been deleted.
        updated (set): a set of API IDs that have been updated.
        subject (str, optional): if provided, replaces the default subject.

    Returns:
        str: a commit message.
    """
    commitmsg = 'Autogenerated update ({})\n'.format(date.today().isoformat())
    if subject:
        commitmsg = '{}\n'.format(subject)
    if added:
        commitmsg += '\nAdd:\n'
        for id_ in sorted(added):
            commitmsg += '- {}\n'.format(id_)
    if deleted:
        commitmsg += '\nDelete:\n'
        for id_ in sorted(deleted):
            commitmsg += '- {}\n'.format(id_)
    if updated:
        commitmsg += '\nUpdate:\n'
        for id_ in sorted(updated):
            commitmsg += '- {}\n'.format(id_)
    return commitmsg
